name: iao
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - filelock==3.20.0
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/iao
