name: iao
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aggdraw==1.3.19
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==6.33.1
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - streamlit
      - altair
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - tzdata==2025.2
      - urllib3==2.6.0
      - visualtorch==0.2.4
      - werkzeug==3.1.3
